In [1]:
import torch

In [3]:
1.44 * (1/12)**0.5 + 0.5

0.9156921938165306

In [4]:
1 > (float('-inf') + 0.1)

True

In [2]:
torch.__version__

'2.5.0'

In [ ]:
import torch; print(f'CUDA available: {torch.cuda.is_available()}');

CUDA available: True
CUDA version: 12.4

In [1]:
import torch

torch.cuda.is_available()

True

In [2]:
import numpy

In [1]:
import sys
sys.path.append("../")

import h5py as h5

from data_manager.processor import process_data
from data_manager.root_extractor import read_root# RootFileReader, MCRootPaths, ExpRootPaths

In [15]:
# MC file reading
path = "/net/62/home3/ivkhar/Baikal/data/initial_data/MC_2020/muatm/root/all/1005.root"
start = 0
stop = None  # read all events
prefix = "muatm1005_"
pulses, events, coords, muons = read_root(path, "MC", start, stop, prefix)
print(f"Data from Monte-Carlo file are extracted as 4 Polars DataFrames:")
print(f"\tPulses:", pulses, "\n")
print(f"\tEvents:", events, "\n")
print(f"\tMuons:", muons, "\n")
print(f"\tCoords:", coords, "\n")

Data from Monte-Carlo file are extracted as 4 Polars DataFrames:
	Pulses: shape: (2_039_149, 5)
┌────────────┬────────────┬─────────────┬───────────┬─────────────────┐
│ PulsesChID ┆ PulsesAmpl ┆ PulsesTime  ┆ PulsesFlg ┆ ev_id           │
│ ---        ┆ ---        ┆ ---         ┆ ---       ┆ ---             │
│ i16        ┆ f32        ┆ f32         ┆ i32       ┆ str             │
╞════════════╪════════════╪═════════════╪═══════════╪═════════════════╡
│ 295        ┆ 0.787575   ┆ 2339.25     ┆ -999999   ┆ muatm1005_0     │
│ 297        ┆ 0.802035   ┆ 3817.687012 ┆ 0         ┆ muatm1005_0     │
│ 304        ┆ 1.158783   ┆ 387.77063   ┆ 0         ┆ muatm1005_0     │
│ 310        ┆ 0.813267   ┆ 2140.404297 ┆ 0         ┆ muatm1005_0     │
│ 311        ┆ 0.220002   ┆ 2921.579102 ┆ 0         ┆ muatm1005_0     │
│ …          ┆ …          ┆ …           ┆ …         ┆ …               │
│ 1719       ┆ 0.370473   ┆ 22.70644    ┆ 0         ┆ muatm1005_32101 │
│ 1720       ┆ 1.053025   ┆ -265.680542 ┆ 0         ┆ muatm1005_32101 │
│ 1723       ┆ 0.315001   ┆ 788.547363  ┆ 0         ┆ muatm1005_32101 │
│ 1724       ┆ 0.975301   ┆ 1382.784058 ┆ 0         ┆ muatm1005_32101 │
│ 1727       ┆ 0.941012   ┆ 2943.951904 ┆ 0         ┆ muatm1005_32101 │
└────────────┴────────────┴─────────────┴───────────┴─────────────────┘

	Events: shape: (32_102, 9)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ PulsesN ┆ PrimeTheta ┆ PrimePhi  ┆ PrimeEn   ┆ … ┆ ResponseM ┆ BundleEnR ┆ EventWeig ┆ ev_id     │
│ ---     ┆ ---        ┆ ---       ┆ ---       ┆   ┆ uN        ┆ eg        ┆ ht        ┆ ---       │
│ i32     ┆ f32        ┆ f32       ┆ f32       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str       │
│         ┆            ┆           ┆           ┆   ┆ i32       ┆ f32       ┆ f32       ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 74      ┆ 138.132187 ┆ 249.20790 ┆ 1182.9426 ┆ … ┆ 14        ┆ 13959.493 ┆ 1.0       ┆ muatm1005 │
│         ┆            ┆ 1         ┆ 27        ┆   ┆           ┆ 164       ┆           ┆ _0        │
│ 67      ┆ 120.961884 ┆ 306.12103 ┆ 31.292971 ┆ … ┆ 1         ┆ 702.91003 ┆ 1.0       ┆ muatm1005 │
│         ┆            ┆ 3         ┆           ┆   ┆           ┆ 4         ┆           ┆ _1        │
│ 49      ┆ 161.2771   ┆ 15.59375  ┆ 2.399302  ┆ … ┆ 1         ┆ 125.76041 ┆ 1.0       ┆ muatm1005 │
│         ┆            ┆           ┆           ┆   ┆           ┆ 4         ┆           ┆ _2        │
│ 54      ┆ 170.644424 ┆ 322.83407 ┆ 3.220376  ┆ … ┆ 1         ┆ 350.66622 ┆ 1.0       ┆ muatm1005 │
│         ┆            ┆ 6         ┆           ┆   ┆           ┆ 9         ┆           ┆ _3        │
│ 73      ┆ 164.90538  ┆ 335.64535 ┆ 1.744232  ┆ … ┆ 1         ┆ 172.82743 ┆ 1.0       ┆ muatm1005 │
│         ┆            ┆ 5         ┆           ┆   ┆           ┆ 8         ┆           ┆ _4        │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 53      ┆ 145.074005 ┆ 147.22229 ┆ 3.8823    ┆ … ┆ 1         ┆ 437.60119 ┆ 1.0       ┆ muatm1005 │
│         ┆            ┆           ┆           ┆   ┆           ┆ 6         ┆           ┆ _32097    │
│ 56      ┆ 160.560928 ┆ 356.16116 ┆ 14.805874 ┆ … ┆ 1         ┆ 3170.6992 ┆ 1.0       ┆ muatm1005 │
│         ┆            ┆ 3         ┆           ┆   ┆           ┆ 19        ┆           ┆ _32098    │
│ 60      ┆ 167.949875 ┆ 241.64872 ┆ 0.748658  ┆ … ┆ 1         ┆ 116.90828 ┆ 1.0       ┆ muatm1005 │
│         ┆            ┆ 7         ┆           ┆   ┆           ┆ 7         ┆           ┆ _32099    │
│ 67      ┆ 156.025513 ┆ 83.964813 ┆ 15.66829  ┆ … ┆ 1         ┆ 1445.8447 ┆ 1.0       ┆ muatm1005 │
│         ┆            ┆           ┆           ┆   ┆           ┆ 27        ┆           ┆ _32100    │
│ 62      ┆ 168.335953 ┆ 102.29211 ┆ 2.497537  ┆ … ┆ 1         ┆ 251.01838 ┆ 1.0       ┆ muatm1005 │
│         ┆            ┆ 4         ┆           ┆   ┆           ┆ 7         ┆           ┆ _32101    │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

	Muons: shape: (126_204, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ RespMuThe ┆ RespMuPhi ┆ RespMuTra ┆ RespMuTra ┆ … ┆ RespMuDel ┆ RespMuEn  ┆ ev_id     ┆ mu_local │
│ ta        ┆ ---       ┆ ckX       ┆ ckY       ┆   ┆ ay        ┆ ---       ┆ ---       ┆ _id      │
│ ---       ┆ f32       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f32       ┆ str       ┆ ---      │
│ f32       ┆           ┆ f32       ┆ f32       ┆   ┆ f32       ┆           ┆           ┆ i16      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 138.13218 ┆ 249.20790 ┆ 75.208809 ┆ 90.936844 ┆ … ┆ 0.0       ┆ 72.838028 ┆ muatm1005 ┆ 0        │
│ 7         ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆ _0        ┆          │
│ 138.13218 ┆ 249.20790 ┆ 85.442429 ┆ 88.96862  ┆ … ┆ 0.0       ┆ 1123.7596 ┆ muatm1005 ┆ 1        │
│ 7         ┆ 1         ┆           ┆           ┆   ┆           ┆ 44        ┆ _0        ┆          │
│ 138.13218 ┆ 249.20790 ┆ 83.68821  ┆ 87.081657 ┆ … ┆ 0.0       ┆ 1790.3575 ┆ muatm1005 ┆ 2        │
│ 7         ┆ 1         ┆           ┆           ┆   ┆           ┆ 44        ┆ _0        ┆          │
│ 138.13218 ┆ 249.20790 ┆ 94.875893 ┆ 81.92321  ┆ … ┆ 0.0       ┆ 221.99206 ┆ muatm1005 ┆ 3        │
│ 7         ┆ 1         ┆           ┆           ┆   ┆           ┆ 5         ┆ _0        ┆          │
│ 138.13218 ┆ 249.20790 ┆ 90.695847 ┆ 83.095505 ┆ … ┆ 0.0       ┆ 124.41235 ┆ muatm1005 ┆ 4        │
│ 7         ┆ 1         ┆           ┆           ┆   ┆           ┆ 4         ┆ _0        ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 145.07400 ┆ 147.22229 ┆ 161.75053 ┆ 183.89013 ┆ … ┆ 0.0       ┆ 125.24692 ┆ muatm1005 ┆ 0        │
│ 5         ┆           ┆ 4         ┆ 7         ┆   ┆           ┆ 5         ┆ _32097    ┆          │
│ 160.56092 ┆ 356.16116 ┆ -101.7913 ┆ -31.63967 ┆ … ┆ 0.0       ┆ 2723.4067 ┆ muatm1005 ┆ 0        │
│ 8         ┆ 3         ┆ 44        ┆ 9         ┆   ┆           ┆ 38        ┆ _32098    ┆          │
│ 167.94987 ┆ 241.64872 ┆ 73.670219 ┆ -245.6079 ┆ … ┆ 0.0       ┆ -15.66184 ┆ muatm1005 ┆ 0        │
│ 5         ┆ 7         ┆           ┆ 1         ┆   ┆           ┆           ┆ _32099    ┆          │
│ 156.02551 ┆ 83.964813 ┆ -9.395959 ┆ 186.32916 ┆ … ┆ 0.0       ┆ 995.82983 ┆ muatm1005 ┆ 0        │
│ 3         ┆           ┆           ┆ 3         ┆   ┆           ┆ 4         ┆ _32100    ┆          │
│ 168.33595 ┆ 102.29211 ┆ -273.3483 ┆ -182.3759 ┆ … ┆ 0.0       ┆ 81.453011 ┆ muatm1005 ┆ 0        │
│ 3         ┆ 4         ┆ 89        ┆           ┆   ┆           ┆           ┆ _32101    ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

	Coords: shape: (64_717_632, 7)
┌─────────────┬────────────┬─────────────┬────────────┬────────────┬───────────┬─────────────────┐
│ X           ┆ Y          ┆ Z           ┆ PulsesChID ┆ cluster_id ┆ string_id ┆ ev_id           │
│ ---         ┆ ---        ┆ ---         ┆ ---        ┆ ---        ┆ ---       ┆ ---             │
│ f64         ┆ f64        ┆ f64         ┆ i16        ┆ i8         ┆ i16       ┆ str             │
╞═════════════╪════════════╪═════════════╪════════════╪════════════╪═══════════╪═════════════════╡
│ 219.135361  ┆ 174.35466  ┆ -262.688141 ┆ 0          ┆ 0          ┆ 0         ┆ muatm1005_0     │
│ 219.135361  ┆ 174.35466  ┆ -247.68013  ┆ 1          ┆ 0          ┆ 0         ┆ muatm1005_0     │
│ 219.135361  ┆ 174.35466  ┆ -232.671127 ┆ 2          ┆ 0          ┆ 0         ┆ muatm1005_0     │
│ 219.135361  ┆ 174.35466  ┆ -217.663147 ┆ 3          ┆ 0          ┆ 0         ┆ muatm1005_0     │
│ 219.135361  ┆ 174.35466  ┆ -202.654129 ┆ 4          ┆ 0          ┆ 0         ┆ muatm1005_0     │
│ …           ┆ …          ┆ …           ┆ …          ┆ …          ┆ …         ┆ …               │
│ -270.653595 ┆ 146.058685 ┆ 203.644836  ┆ 2011       ┆ 6          ┆ 55        ┆ muatm1005_32101 │
│ -270.653595 ┆ 146.058685 ┆ 218.650818  ┆ 2012       ┆ 6          ┆ 55        ┆ muatm1005_32101 │
│ -270.653595 ┆ 146.058685 ┆ 233.655807  ┆ 2013       ┆ 6          ┆ 55        ┆ muatm1005_32101 │
│ -270.653595 ┆ 146.058685 ┆ 248.661865  ┆ 2014       ┆ 6          ┆ 55        ┆ muatm1005_32101 │
│ -270.653595 ┆ 146.058685 ┆ 263.66687   ┆ 2015       ┆ 6          ┆ 55        ┆ muatm1005_32101 │
└─────────────┴────────────┴─────────────┴────────────┴────────────┴───────────┴─────────────────┘

In [16]:
events

shape: (32_102, 9)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ PulsesN ┆ PrimeTheta ┆ PrimePhi  ┆ PrimeEn   ┆ … ┆ ResponseM ┆ BundleEnR ┆ EventWeig ┆ ev_id     │
│ ---     ┆ ---        ┆ ---       ┆ ---       ┆   ┆ uN        ┆ eg        ┆ ht        ┆ ---       │
│ i32     ┆ f32        ┆ f32       ┆ f32       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str       │
│         ┆            ┆           ┆           ┆   ┆ i32       ┆ f32       ┆ f32       ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 74      ┆ 138.132187 ┆ 249.20790 ┆ 1182.9426 ┆ … ┆ 14        ┆ 13959.493 ┆ 1.0       ┆ muatm1005 │
│         ┆            ┆ 1         ┆ 27        ┆   ┆           ┆ 164       ┆           ┆ _0        │
│ 67      ┆ 120.961884 ┆ 306.12103 ┆ 31.292971 ┆ … ┆ 1         ┆ 702.91003 ┆ 1.0       ┆ muatm1005 │
│         ┆            ┆ 3         ┆           ┆   ┆           ┆ 4         ┆           ┆ _1        │
│ 49      ┆ 161.2771   ┆ 15.59375  ┆ 2.399302  ┆ … ┆ 1         ┆ 125.76041 ┆ 1.0       ┆ muatm1005 │
│         ┆            ┆           ┆           ┆   ┆           ┆ 4         ┆           ┆ _2        │
│ 54      ┆ 170.644424 ┆ 322.83407 ┆ 3.220376  ┆ … ┆ 1         ┆ 350.66622 ┆ 1.0       ┆ muatm1005 │
│         ┆            ┆ 6         ┆           ┆   ┆           ┆ 9         ┆           ┆ _3        │
│ 73      ┆ 164.90538  ┆ 335.64535 ┆ 1.744232  ┆ … ┆ 1         ┆ 172.82743 ┆ 1.0       ┆ muatm1005 │
│         ┆            ┆ 5         ┆           ┆   ┆           ┆ 8         ┆           ┆ _4        │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 53      ┆ 145.074005 ┆ 147.22229 ┆ 3.8823    ┆ … ┆ 1         ┆ 437.60119 ┆ 1.0       ┆ muatm1005 │
│         ┆            ┆           ┆           ┆   ┆           ┆ 6         ┆           ┆ _32097    │
│ 56      ┆ 160.560928 ┆ 356.16116 ┆ 14.805874 ┆ … ┆ 1         ┆ 3170.6992 ┆ 1.0       ┆ muatm1005 │
│         ┆            ┆ 3         ┆           ┆   ┆           ┆ 19        ┆           ┆ _32098    │
│ 60      ┆ 167.949875 ┆ 241.64872 ┆ 0.748658  ┆ … ┆ 1         ┆ 116.90828 ┆ 1.0       ┆ muatm1005 │
│         ┆            ┆ 7         ┆           ┆   ┆           ┆ 7         ┆           ┆ _32099    │
│ 67      ┆ 156.025513 ┆ 83.964813 ┆ 15.66829  ┆ … ┆ 1         ┆ 1445.8447 ┆ 1.0       ┆ muatm1005 │
│         ┆            ┆           ┆           ┆   ┆           ┆ 27        ┆           ┆ _32100    │
│ 62      ┆ 168.335953 ┆ 102.29211 ┆ 2.497537  ┆ … ┆ 1         ┆ 251.01838 ┆ 1.0       ┆ muatm1005 │
│         ┆            ┆ 4         ┆           ┆   ┆           ┆ 7         ┆           ┆ _32101    │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [11]:
coords

shape: (64_717_632, 7)
┌─────────────┬────────────┬─────────────┬────────────┬────────────┬───────────┬───────┐
│ X           ┆ Y          ┆ Z           ┆ PulsesChID ┆ cluster_id ┆ string_id ┆ ev_id │
│ ---         ┆ ---        ┆ ---         ┆ ---        ┆ ---        ┆ ---       ┆ ---   │
│ f64         ┆ f64        ┆ f64         ┆ i16        ┆ i8         ┆ i16       ┆ str   │
╞═════════════╪════════════╪═════════════╪════════════╪════════════╪═══════════╪═══════╡
│ 219.135361  ┆ 174.35466  ┆ -262.688141 ┆ 0          ┆ 0          ┆ 0         ┆ 0     │
│ 219.135361  ┆ 174.35466  ┆ -247.68013  ┆ 1          ┆ 0          ┆ 0         ┆ 0     │
│ 219.135361  ┆ 174.35466  ┆ -232.671127 ┆ 2          ┆ 0          ┆ 0         ┆ 0     │
│ 219.135361  ┆ 174.35466  ┆ -217.663147 ┆ 3          ┆ 0          ┆ 0         ┆ 0     │
│ 219.135361  ┆ 174.35466  ┆ -202.654129 ┆ 4          ┆ 0          ┆ 0         ┆ 0     │
│ …           ┆ …          ┆ …           ┆ …          ┆ …          ┆ …         ┆ …     │
│ -270.653595 ┆ 146.058685 ┆ 203.644836  ┆ 2011       ┆ 6          ┆ 55        ┆ 32101 │
│ -270.653595 ┆ 146.058685 ┆ 218.650818  ┆ 2012       ┆ 6          ┆ 55        ┆ 32101 │
│ -270.653595 ┆ 146.058685 ┆ 233.655807  ┆ 2013       ┆ 6          ┆ 55        ┆ 32101 │
│ -270.653595 ┆ 146.058685 ┆ 248.661865  ┆ 2014       ┆ 6          ┆ 55        ┆ 32101 │
│ -270.653595 ┆ 146.058685 ┆ 263.66687   ┆ 2015       ┆ 6          ┆ 55        ┆ 32101 │
└─────────────┴────────────┴─────────────┴────────────┴────────────┴───────────┴───────┘

In [17]:
muons

shape: (126_204, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ RespMuThe ┆ RespMuPhi ┆ RespMuTra ┆ RespMuTra ┆ … ┆ RespMuDel ┆ RespMuEn  ┆ ev_id     ┆ mu_local │
│ ta        ┆ ---       ┆ ckX       ┆ ckY       ┆   ┆ ay        ┆ ---       ┆ ---       ┆ _id      │
│ ---       ┆ f32       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f32       ┆ str       ┆ ---      │
│ f32       ┆           ┆ f32       ┆ f32       ┆   ┆ f32       ┆           ┆           ┆ i16      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 138.13218 ┆ 249.20790 ┆ 75.208809 ┆ 90.936844 ┆ … ┆ 0.0       ┆ 72.838028 ┆ muatm1005 ┆ 0        │
│ 7         ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆ _0        ┆          │
│ 138.13218 ┆ 249.20790 ┆ 85.442429 ┆ 88.96862  ┆ … ┆ 0.0       ┆ 1123.7596 ┆ muatm1005 ┆ 1        │
│ 7         ┆ 1         ┆           ┆           ┆   ┆           ┆ 44        ┆ _0        ┆          │
│ 138.13218 ┆ 249.20790 ┆ 83.68821  ┆ 87.081657 ┆ … ┆ 0.0       ┆ 1790.3575 ┆ muatm1005 ┆ 2        │
│ 7         ┆ 1         ┆           ┆           ┆   ┆           ┆ 44        ┆ _0        ┆          │
│ 138.13218 ┆ 249.20790 ┆ 94.875893 ┆ 81.92321  ┆ … ┆ 0.0       ┆ 221.99206 ┆ muatm1005 ┆ 3        │
│ 7         ┆ 1         ┆           ┆           ┆   ┆           ┆ 5         ┆ _0        ┆          │
│ 138.13218 ┆ 249.20790 ┆ 90.695847 ┆ 83.095505 ┆ … ┆ 0.0       ┆ 124.41235 ┆ muatm1005 ┆ 4        │
│ 7         ┆ 1         ┆           ┆           ┆   ┆           ┆ 4         ┆ _0        ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 145.07400 ┆ 147.22229 ┆ 161.75053 ┆ 183.89013 ┆ … ┆ 0.0       ┆ 125.24692 ┆ muatm1005 ┆ 0        │
│ 5         ┆           ┆ 4         ┆ 7         ┆   ┆           ┆ 5         ┆ _32097    ┆          │
│ 160.56092 ┆ 356.16116 ┆ -101.7913 ┆ -31.63967 ┆ … ┆ 0.0       ┆ 2723.4067 ┆ muatm1005 ┆ 0        │
│ 8         ┆ 3         ┆ 44        ┆ 9         ┆   ┆           ┆ 38        ┆ _32098    ┆          │
│ 167.94987 ┆ 241.64872 ┆ 73.670219 ┆ -245.6079 ┆ … ┆ 0.0       ┆ -15.66184 ┆ muatm1005 ┆ 0        │
│ 5         ┆ 7         ┆           ┆ 1         ┆   ┆           ┆           ┆ _32099    ┆          │
│ 156.02551 ┆ 83.964813 ┆ -9.395959 ┆ 186.32916 ┆ … ┆ 0.0       ┆ 995.82983 ┆ muatm1005 ┆ 0        │
│ 3         ┆           ┆           ┆ 3         ┆   ┆           ┆ 4         ┆ _32100    ┆          │
│ 168.33595 ┆ 102.29211 ┆ -273.3483 ┆ -182.3759 ┆ … ┆ 0.0       ┆ 81.453011 ┆ muatm1005 ┆ 0        │
│ 3         ┆ 4         ┆ 89        ┆           ┆   ┆           ┆           ┆ _32101    ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
h5path = "/net/62/home3/ivkhar/Baikal/data/h5s/baikal_mc2020_multi_split_0924.h5"

with h5.File(h5path, "r") as f:
    f1 = f['muatm']
    print(f1.keys())
    for k in f1.keys():
        print(k)
        #print(f1[k]['data'][:])
        #break
        print(f1[k]['data'].shape, f1[k]['data'].dtype)

<KeysViewHDF5 ['clusters_centers', 'coords_are_cluster_centered', 'ev_ids', 'muons_prty', 'prime_prty', 'raw']>
clusters_centers
(7, 3) float64
coords_are_cluster_centered
() bool
ev_ids

KeyError: "Unable to synchronously open object (object 'data' doesn't exist)"